[package]
name = "parallel2"
version = "0.1.0"
edition = "2024"
[profile.bench]
lto = true
[dependencies]
lazy_static = "1.5.0"
libc = "0.2.172"
rand = "0.9.1"
rayon = "1.10.0"

[build-dependencies]
cc = "1.2.26"
